// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  addProjectMembers,
  checkSlugAvailability,
  createProject,
  createUser,
  deleteProject,
  deleteUser,
  deployProject,
  getProjectById,
  getProjectBySlug,
  getProjectDockerStatus,
  getProjectLogs,
  getProjects,
  getUserById,
  getUsers,
  login,
  logout,
  type Options,
  refreshToken,
  removeProjectContainers,
  removeProjectMembers,
  restartProject,
  stopProject,
  updateComposeFile,
  updateProject,
  updateUser,
} from "../sdk.gen";
import type {
  AddProjectMembersData,
  AddProjectMembersError,
  AddProjectMembersResponse,
  CheckSlugAvailabilityData,
  CheckSlugAvailabilityResponse,
  CreateProjectData,
  CreateProjectError,
  CreateProjectResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteProjectData,
  DeleteProjectError,
  DeleteUserData,
  DeleteUserError,
  DeployProjectData,
  DeployProjectError,
  DeployProjectResponse,
  GetProjectByIdData,
  GetProjectByIdError,
  GetProjectByIdResponse,
  GetProjectBySlugData,
  GetProjectBySlugError,
  GetProjectBySlugResponse,
  GetProjectDockerStatusData,
  GetProjectDockerStatusError,
  GetProjectDockerStatusResponse,
  GetProjectLogsData,
  GetProjectLogsError,
  GetProjectLogsResponse,
  GetProjectsData,
  GetProjectsResponse,
  GetUserByIdData,
  GetUserByIdError,
  GetUserByIdResponse,
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  LoginData,
  LoginError,
  LoginResponse,
  LogoutData,
  LogoutError,
  LogoutResponse,
  RefreshTokenData,
  RefreshTokenError,
  RefreshTokenResponse,
  RemoveProjectContainersData,
  RemoveProjectContainersError,
  RemoveProjectContainersResponse,
  RemoveProjectMembersData,
  RemoveProjectMembersError,
  RemoveProjectMembersResponse,
  RestartProjectData,
  RestartProjectError,
  RestartProjectResponse,
  StopProjectData,
  StopProjectError,
  StopProjectResponse,
  UpdateComposeFileData,
  UpdateComposeFileError,
  UpdateComposeFileResponse,
  UpdateProjectData,
  UpdateProjectError,
  UpdateProjectResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey("getUsers", options);

/**
 * Get all users (Admin only)
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
  queryOptions<
    GetUsersResponse,
    GetUsersError,
    GetUsersResponse,
    ReturnType<typeof getUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });

/**
 * Create a new user (Admin only)
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user (Admin only)
 */
export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>,
): UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserError,
    Options<DeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) =>
  createQueryKey("getUserById", options);

/**
 * Get user by ID (Admin only)
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) =>
  queryOptions<
    GetUserByIdResponse,
    GetUserByIdError,
    GetUserByIdResponse,
    ReturnType<typeof getUserByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserByIdQueryKey(options),
  });

/**
 * Update a user (Admin only)
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<
  UpdateUserResponse,
  UpdateUserError,
  Options<UpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectsQueryKey = (options?: Options<GetProjectsData>) =>
  createQueryKey("getProjects", options);

/**
 * Get all projects for the current user
 */
export const getProjectsOptions = (options?: Options<GetProjectsData>) =>
  queryOptions<
    GetProjectsResponse,
    DefaultError,
    GetProjectsResponse,
    ReturnType<typeof getProjectsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectsQueryKey(options),
  });

/**
 * Create a new project (Admin only)
 */
export const createProjectMutation = (
  options?: Partial<Options<CreateProjectData>>,
): UseMutationOptions<
  CreateProjectResponse,
  CreateProjectError,
  Options<CreateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateProjectResponse,
    CreateProjectError,
    Options<CreateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a project (Admin only)
 */
export const deleteProjectMutation = (
  options?: Partial<Options<DeleteProjectData>>,
): UseMutationOptions<
  unknown,
  DeleteProjectError,
  Options<DeleteProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteProjectError,
    Options<DeleteProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectByIdQueryKey = (options: Options<GetProjectByIdData>) =>
  createQueryKey("getProjectById", options);

/**
 * Get project by ID
 */
export const getProjectByIdOptions = (options: Options<GetProjectByIdData>) =>
  queryOptions<
    GetProjectByIdResponse,
    GetProjectByIdError,
    GetProjectByIdResponse,
    ReturnType<typeof getProjectByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectByIdQueryKey(options),
  });

/**
 * Update a project (Admin only)
 */
export const updateProjectMutation = (
  options?: Partial<Options<UpdateProjectData>>,
): UseMutationOptions<
  UpdateProjectResponse,
  UpdateProjectError,
  Options<UpdateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProjectResponse,
    UpdateProjectError,
    Options<UpdateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectBySlugQueryKey = (
  options: Options<GetProjectBySlugData>,
) => createQueryKey("getProjectBySlug", options);

/**
 * Get project by slug
 */
export const getProjectBySlugOptions = (
  options: Options<GetProjectBySlugData>,
) =>
  queryOptions<
    GetProjectBySlugResponse,
    GetProjectBySlugError,
    GetProjectBySlugResponse,
    ReturnType<typeof getProjectBySlugQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectBySlugQueryKey(options),
  });

export const checkSlugAvailabilityQueryKey = (
  options: Options<CheckSlugAvailabilityData>,
) => createQueryKey("checkSlugAvailability", options);

/**
 * Check if a slug is available
 */
export const checkSlugAvailabilityOptions = (
  options: Options<CheckSlugAvailabilityData>,
) =>
  queryOptions<
    CheckSlugAvailabilityResponse,
    DefaultError,
    CheckSlugAvailabilityResponse,
    ReturnType<typeof checkSlugAvailabilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkSlugAvailability({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: checkSlugAvailabilityQueryKey(options),
  });

/**
 * Add members to a project (Admin only)
 */
export const addProjectMembersMutation = (
  options?: Partial<Options<AddProjectMembersData>>,
): UseMutationOptions<
  AddProjectMembersResponse,
  AddProjectMembersError,
  Options<AddProjectMembersData>
> => {
  const mutationOptions: UseMutationOptions<
    AddProjectMembersResponse,
    AddProjectMembersError,
    Options<AddProjectMembersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addProjectMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove members from a project (Admin only)
 */
export const removeProjectMembersMutation = (
  options?: Partial<Options<RemoveProjectMembersData>>,
): UseMutationOptions<
  RemoveProjectMembersResponse,
  RemoveProjectMembersError,
  Options<RemoveProjectMembersData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveProjectMembersResponse,
    RemoveProjectMembersError,
    Options<RemoveProjectMembersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeProjectMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update project compose file (Admin only)
 */
export const updateComposeFileMutation = (
  options?: Partial<Options<UpdateComposeFileData>>,
): UseMutationOptions<
  UpdateComposeFileResponse,
  UpdateComposeFileError,
  Options<UpdateComposeFileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateComposeFileResponse,
    UpdateComposeFileError,
    Options<UpdateComposeFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateComposeFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Deploy project containers (Admin only)
 */
export const deployProjectMutation = (
  options?: Partial<Options<DeployProjectData>>,
): UseMutationOptions<
  DeployProjectResponse,
  DeployProjectError,
  Options<DeployProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    DeployProjectResponse,
    DeployProjectError,
    Options<DeployProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deployProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Stop project containers (Admin only)
 */
export const stopProjectMutation = (
  options?: Partial<Options<StopProjectData>>,
): UseMutationOptions<
  StopProjectResponse,
  StopProjectError,
  Options<StopProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    StopProjectResponse,
    StopProjectError,
    Options<StopProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await stopProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Restart project containers (Admin only)
 */
export const restartProjectMutation = (
  options?: Partial<Options<RestartProjectData>>,
): UseMutationOptions<
  RestartProjectResponse,
  RestartProjectError,
  Options<RestartProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    RestartProjectResponse,
    RestartProjectError,
    Options<RestartProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await restartProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove project containers and deployment files (Admin only)
 */
export const removeProjectContainersMutation = (
  options?: Partial<Options<RemoveProjectContainersData>>,
): UseMutationOptions<
  RemoveProjectContainersResponse,
  RemoveProjectContainersError,
  Options<RemoveProjectContainersData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveProjectContainersResponse,
    RemoveProjectContainersError,
    Options<RemoveProjectContainersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeProjectContainers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectDockerStatusQueryKey = (
  options: Options<GetProjectDockerStatusData>,
) => createQueryKey("getProjectDockerStatus", options);

/**
 * Get project deployment status
 */
export const getProjectDockerStatusOptions = (
  options: Options<GetProjectDockerStatusData>,
) =>
  queryOptions<
    GetProjectDockerStatusResponse,
    GetProjectDockerStatusError,
    GetProjectDockerStatusResponse,
    ReturnType<typeof getProjectDockerStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectDockerStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectDockerStatusQueryKey(options),
  });

export const getProjectLogsQueryKey = (options: Options<GetProjectLogsData>) =>
  createQueryKey("getProjectLogs", options);

/**
 * Get project container logs
 */
export const getProjectLogsOptions = (options: Options<GetProjectLogsData>) =>
  queryOptions<
    GetProjectLogsResponse,
    GetProjectLogsError,
    GetProjectLogsResponse,
    ReturnType<typeof getProjectLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectLogsQueryKey(options),
  });

/**
 * Authenticate user and return access token
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    LoginError,
    Options<LoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh access token using refresh token cookie
 */
export const refreshTokenMutation = (
  options?: Partial<Options<RefreshTokenData>>,
): UseMutationOptions<
  RefreshTokenResponse,
  RefreshTokenError,
  Options<RefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshTokenResponse,
    RefreshTokenError,
    Options<RefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout and invalidate tokens
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    LogoutError,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
