// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  addProjectMembers,
  applyTemplate,
  checkSlugAvailability,
  createConfig,
  createEnvironment,
  createNetwork,
  createProject,
  createSecret,
  createService,
  createUser,
  createVolume,
  deleteConfig,
  deleteEnvironment,
  deleteNetwork,
  deleteProject,
  deleteSecret,
  deleteService,
  deleteUser,
  deleteVolume,
  getConfigs,
  getEnvironmentBySlug,
  getEnvironments,
  getNetworks,
  getProjectById,
  getProjectBySlug,
  getProjects,
  getSecrets,
  getServiceById,
  getServices,
  getTemplates,
  getUserById,
  getUsers,
  getVolumes,
  login,
  logout,
  type Options,
  refreshToken,
  removeProjectMembers,
  updateConfig,
  updateProject,
  updateSecret,
  updateService,
  updateUser,
} from "../sdk.gen";
import type {
  AddProjectMembersData,
  AddProjectMembersError,
  AddProjectMembersResponse,
  ApplyTemplateData,
  ApplyTemplateError,
  ApplyTemplateResponse,
  CheckSlugAvailabilityData,
  CheckSlugAvailabilityResponse,
  CreateConfigData,
  CreateConfigError,
  CreateConfigResponse,
  CreateEnvironmentData,
  CreateEnvironmentError,
  CreateEnvironmentResponse,
  CreateNetworkData,
  CreateNetworkError,
  CreateNetworkResponse,
  CreateProjectData,
  CreateProjectError,
  CreateProjectResponse,
  CreateSecretData,
  CreateSecretError,
  CreateSecretResponse,
  CreateServiceData,
  CreateServiceError,
  CreateServiceResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  CreateVolumeData,
  CreateVolumeError,
  CreateVolumeResponse,
  DeleteConfigData,
  DeleteConfigError,
  DeleteConfigResponse,
  DeleteEnvironmentData,
  DeleteEnvironmentError,
  DeleteEnvironmentResponse,
  DeleteNetworkData,
  DeleteNetworkError,
  DeleteNetworkResponse,
  DeleteProjectData,
  DeleteProjectError,
  DeleteSecretData,
  DeleteSecretError,
  DeleteSecretResponse,
  DeleteServiceData,
  DeleteServiceError,
  DeleteServiceResponse,
  DeleteUserData,
  DeleteUserError,
  DeleteVolumeData,
  DeleteVolumeError,
  DeleteVolumeResponse,
  GetConfigsData,
  GetConfigsError,
  GetConfigsResponse,
  GetEnvironmentBySlugData,
  GetEnvironmentBySlugError,
  GetEnvironmentBySlugResponse,
  GetEnvironmentsData,
  GetEnvironmentsError,
  GetEnvironmentsResponse,
  GetNetworksData,
  GetNetworksError,
  GetNetworksResponse,
  GetProjectByIdData,
  GetProjectByIdError,
  GetProjectByIdResponse,
  GetProjectBySlugData,
  GetProjectBySlugError,
  GetProjectBySlugResponse,
  GetProjectsData,
  GetProjectsResponse,
  GetSecretsData,
  GetSecretsError,
  GetSecretsResponse,
  GetServiceByIdData,
  GetServiceByIdError,
  GetServiceByIdResponse,
  GetServicesData,
  GetServicesError,
  GetServicesResponse,
  GetTemplatesData,
  GetTemplatesResponse,
  GetUserByIdData,
  GetUserByIdError,
  GetUserByIdResponse,
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  GetVolumesData,
  GetVolumesError,
  GetVolumesResponse,
  LoginData,
  LoginError,
  LoginResponse,
  LogoutData,
  LogoutError,
  LogoutResponse,
  RefreshTokenData,
  RefreshTokenError,
  RefreshTokenResponse,
  RemoveProjectMembersData,
  RemoveProjectMembersError,
  RemoveProjectMembersResponse,
  UpdateConfigData,
  UpdateConfigError,
  UpdateConfigResponse,
  UpdateProjectData,
  UpdateProjectError,
  UpdateProjectResponse,
  UpdateSecretData,
  UpdateSecretError,
  UpdateSecretResponse,
  UpdateServiceData,
  UpdateServiceError,
  UpdateServiceResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getTemplatesQueryKey = (options?: Options<GetTemplatesData>) =>
  createQueryKey("getTemplates", options);

/**
 * Get all available templates
 */
export const getTemplatesOptions = (options?: Options<GetTemplatesData>) =>
  queryOptions<
    GetTemplatesResponse,
    DefaultError,
    GetTemplatesResponse,
    ReturnType<typeof getTemplatesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTemplates({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTemplatesQueryKey(options),
  });

/**
 * Apply a template to create services in an environment
 */
export const applyTemplateMutation = (
  options?: Partial<Options<ApplyTemplateData>>,
): UseMutationOptions<
  ApplyTemplateResponse,
  ApplyTemplateError,
  Options<ApplyTemplateData>
> => {
  const mutationOptions: UseMutationOptions<
    ApplyTemplateResponse,
    ApplyTemplateError,
    Options<ApplyTemplateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await applyTemplate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getVolumesQueryKey = (options: Options<GetVolumesData>) =>
  createQueryKey("getVolumes", options);

/**
 * Get all volumes in an environment
 */
export const getVolumesOptions = (options: Options<GetVolumesData>) =>
  queryOptions<
    GetVolumesResponse,
    GetVolumesError,
    GetVolumesResponse,
    ReturnType<typeof getVolumesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getVolumes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getVolumesQueryKey(options),
  });

/**
 * Create a new volume
 */
export const createVolumeMutation = (
  options?: Partial<Options<CreateVolumeData>>,
): UseMutationOptions<
  CreateVolumeResponse,
  CreateVolumeError,
  Options<CreateVolumeData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateVolumeResponse,
    CreateVolumeError,
    Options<CreateVolumeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createVolume({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a volume
 */
export const deleteVolumeMutation = (
  options?: Partial<Options<DeleteVolumeData>>,
): UseMutationOptions<
  DeleteVolumeResponse,
  DeleteVolumeError,
  Options<DeleteVolumeData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteVolumeResponse,
    DeleteVolumeError,
    Options<DeleteVolumeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteVolume({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey("getUsers", options);

/**
 * Get all users (Admin only)
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
  queryOptions<
    GetUsersResponse,
    GetUsersError,
    GetUsersResponse,
    ReturnType<typeof getUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });

/**
 * Create a new user (Admin only)
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user (Admin only)
 */
export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>,
): UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserError,
    Options<DeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) =>
  createQueryKey("getUserById", options);

/**
 * Get user by ID (Admin only)
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) =>
  queryOptions<
    GetUserByIdResponse,
    GetUserByIdError,
    GetUserByIdResponse,
    ReturnType<typeof getUserByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserByIdQueryKey(options),
  });

/**
 * Update a user (Admin only)
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<
  UpdateUserResponse,
  UpdateUserError,
  Options<UpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getServicesQueryKey = (options: Options<GetServicesData>) =>
  createQueryKey("getServices", options);

/**
 * Get all services in an environment
 */
export const getServicesOptions = (options: Options<GetServicesData>) =>
  queryOptions<
    GetServicesResponse,
    GetServicesError,
    GetServicesResponse,
    ReturnType<typeof getServicesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getServices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getServicesQueryKey(options),
  });

/**
 * Create a new service
 */
export const createServiceMutation = (
  options?: Partial<Options<CreateServiceData>>,
): UseMutationOptions<
  CreateServiceResponse,
  CreateServiceError,
  Options<CreateServiceData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateServiceResponse,
    CreateServiceError,
    Options<CreateServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a service
 */
export const deleteServiceMutation = (
  options?: Partial<Options<DeleteServiceData>>,
): UseMutationOptions<
  DeleteServiceResponse,
  DeleteServiceError,
  Options<DeleteServiceData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteServiceResponse,
    DeleteServiceError,
    Options<DeleteServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getServiceByIdQueryKey = (options: Options<GetServiceByIdData>) =>
  createQueryKey("getServiceById", options);

/**
 * Get service details by ID
 */
export const getServiceByIdOptions = (options: Options<GetServiceByIdData>) =>
  queryOptions<
    GetServiceByIdResponse,
    GetServiceByIdError,
    GetServiceByIdResponse,
    ReturnType<typeof getServiceByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getServiceById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getServiceByIdQueryKey(options),
  });

/**
 * Update a service
 */
export const updateServiceMutation = (
  options?: Partial<Options<UpdateServiceData>>,
): UseMutationOptions<
  UpdateServiceResponse,
  UpdateServiceError,
  Options<UpdateServiceData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateServiceResponse,
    UpdateServiceError,
    Options<UpdateServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSecretsQueryKey = (options: Options<GetSecretsData>) =>
  createQueryKey("getSecrets", options);

/**
 * Get all secrets in an environment
 */
export const getSecretsOptions = (options: Options<GetSecretsData>) =>
  queryOptions<
    GetSecretsResponse,
    GetSecretsError,
    GetSecretsResponse,
    ReturnType<typeof getSecretsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSecrets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSecretsQueryKey(options),
  });

/**
 * Create a new secret
 */
export const createSecretMutation = (
  options?: Partial<Options<CreateSecretData>>,
): UseMutationOptions<
  CreateSecretResponse,
  CreateSecretError,
  Options<CreateSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSecretResponse,
    CreateSecretError,
    Options<CreateSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a secret
 */
export const deleteSecretMutation = (
  options?: Partial<Options<DeleteSecretData>>,
): UseMutationOptions<
  DeleteSecretResponse,
  DeleteSecretError,
  Options<DeleteSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSecretResponse,
    DeleteSecretError,
    Options<DeleteSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update a secret
 */
export const updateSecretMutation = (
  options?: Partial<Options<UpdateSecretData>>,
): UseMutationOptions<
  UpdateSecretResponse,
  UpdateSecretError,
  Options<UpdateSecretData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSecretResponse,
    UpdateSecretError,
    Options<UpdateSecretData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectsQueryKey = (options?: Options<GetProjectsData>) =>
  createQueryKey("getProjects", options);

/**
 * Get all projects for the current user
 */
export const getProjectsOptions = (options?: Options<GetProjectsData>) =>
  queryOptions<
    GetProjectsResponse,
    DefaultError,
    GetProjectsResponse,
    ReturnType<typeof getProjectsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectsQueryKey(options),
  });

/**
 * Create a new project (Admin only)
 */
export const createProjectMutation = (
  options?: Partial<Options<CreateProjectData>>,
): UseMutationOptions<
  CreateProjectResponse,
  CreateProjectError,
  Options<CreateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateProjectResponse,
    CreateProjectError,
    Options<CreateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a project (Admin only)
 */
export const deleteProjectMutation = (
  options?: Partial<Options<DeleteProjectData>>,
): UseMutationOptions<
  unknown,
  DeleteProjectError,
  Options<DeleteProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteProjectError,
    Options<DeleteProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectByIdQueryKey = (options: Options<GetProjectByIdData>) =>
  createQueryKey("getProjectById", options);

/**
 * Get project by ID
 */
export const getProjectByIdOptions = (options: Options<GetProjectByIdData>) =>
  queryOptions<
    GetProjectByIdResponse,
    GetProjectByIdError,
    GetProjectByIdResponse,
    ReturnType<typeof getProjectByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectByIdQueryKey(options),
  });

/**
 * Update a project (Admin only)
 */
export const updateProjectMutation = (
  options?: Partial<Options<UpdateProjectData>>,
): UseMutationOptions<
  UpdateProjectResponse,
  UpdateProjectError,
  Options<UpdateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProjectResponse,
    UpdateProjectError,
    Options<UpdateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProjectBySlugQueryKey = (
  options: Options<GetProjectBySlugData>,
) => createQueryKey("getProjectBySlug", options);

/**
 * Get project by slug
 */
export const getProjectBySlugOptions = (
  options: Options<GetProjectBySlugData>,
) =>
  queryOptions<
    GetProjectBySlugResponse,
    GetProjectBySlugError,
    GetProjectBySlugResponse,
    ReturnType<typeof getProjectBySlugQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProjectBySlugQueryKey(options),
  });

export const checkSlugAvailabilityQueryKey = (
  options: Options<CheckSlugAvailabilityData>,
) => createQueryKey("checkSlugAvailability", options);

/**
 * Check if a slug is available
 */
export const checkSlugAvailabilityOptions = (
  options: Options<CheckSlugAvailabilityData>,
) =>
  queryOptions<
    CheckSlugAvailabilityResponse,
    DefaultError,
    CheckSlugAvailabilityResponse,
    ReturnType<typeof checkSlugAvailabilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkSlugAvailability({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: checkSlugAvailabilityQueryKey(options),
  });

/**
 * Add members to a project (Admin only)
 */
export const addProjectMembersMutation = (
  options?: Partial<Options<AddProjectMembersData>>,
): UseMutationOptions<
  AddProjectMembersResponse,
  AddProjectMembersError,
  Options<AddProjectMembersData>
> => {
  const mutationOptions: UseMutationOptions<
    AddProjectMembersResponse,
    AddProjectMembersError,
    Options<AddProjectMembersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addProjectMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove members from a project (Admin only)
 */
export const removeProjectMembersMutation = (
  options?: Partial<Options<RemoveProjectMembersData>>,
): UseMutationOptions<
  RemoveProjectMembersResponse,
  RemoveProjectMembersError,
  Options<RemoveProjectMembersData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveProjectMembersResponse,
    RemoveProjectMembersError,
    Options<RemoveProjectMembersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeProjectMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNetworksQueryKey = (options: Options<GetNetworksData>) =>
  createQueryKey("getNetworks", options);

/**
 * Get all networks in an environment
 */
export const getNetworksOptions = (options: Options<GetNetworksData>) =>
  queryOptions<
    GetNetworksResponse,
    GetNetworksError,
    GetNetworksResponse,
    ReturnType<typeof getNetworksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNetworks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNetworksQueryKey(options),
  });

/**
 * Create a new network
 */
export const createNetworkMutation = (
  options?: Partial<Options<CreateNetworkData>>,
): UseMutationOptions<
  CreateNetworkResponse,
  CreateNetworkError,
  Options<CreateNetworkData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateNetworkResponse,
    CreateNetworkError,
    Options<CreateNetworkData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createNetwork({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a network
 */
export const deleteNetworkMutation = (
  options?: Partial<Options<DeleteNetworkData>>,
): UseMutationOptions<
  DeleteNetworkResponse,
  DeleteNetworkError,
  Options<DeleteNetworkData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteNetworkResponse,
    DeleteNetworkError,
    Options<DeleteNetworkData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteNetwork({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEnvironmentsQueryKey = (
  options: Options<GetEnvironmentsData>,
) => createQueryKey("getEnvironments", options);

/**
 * Get all environments for a project
 */
export const getEnvironmentsOptions = (options: Options<GetEnvironmentsData>) =>
  queryOptions<
    GetEnvironmentsResponse,
    GetEnvironmentsError,
    GetEnvironmentsResponse,
    ReturnType<typeof getEnvironmentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentsQueryKey(options),
  });

/**
 * Create a new environment (Admin only)
 */
export const createEnvironmentMutation = (
  options?: Partial<Options<CreateEnvironmentData>>,
): UseMutationOptions<
  CreateEnvironmentResponse,
  CreateEnvironmentError,
  Options<CreateEnvironmentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateEnvironmentResponse,
    CreateEnvironmentError,
    Options<CreateEnvironmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an environment (Admin only)
 */
export const deleteEnvironmentMutation = (
  options?: Partial<Options<DeleteEnvironmentData>>,
): UseMutationOptions<
  DeleteEnvironmentResponse,
  DeleteEnvironmentError,
  Options<DeleteEnvironmentData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteEnvironmentResponse,
    DeleteEnvironmentError,
    Options<DeleteEnvironmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEnvironmentBySlugQueryKey = (
  options: Options<GetEnvironmentBySlugData>,
) => createQueryKey("getEnvironmentBySlug", options);

/**
 * Get environment details by slug
 */
export const getEnvironmentBySlugOptions = (
  options: Options<GetEnvironmentBySlugData>,
) =>
  queryOptions<
    GetEnvironmentBySlugResponse,
    GetEnvironmentBySlugError,
    GetEnvironmentBySlugResponse,
    ReturnType<typeof getEnvironmentBySlugQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentBySlugQueryKey(options),
  });

export const getConfigsQueryKey = (options: Options<GetConfigsData>) =>
  createQueryKey("getConfigs", options);

/**
 * Get all configs in an environment
 */
export const getConfigsOptions = (options: Options<GetConfigsData>) =>
  queryOptions<
    GetConfigsResponse,
    GetConfigsError,
    GetConfigsResponse,
    ReturnType<typeof getConfigsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConfigs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getConfigsQueryKey(options),
  });

/**
 * Create a new config
 */
export const createConfigMutation = (
  options?: Partial<Options<CreateConfigData>>,
): UseMutationOptions<
  CreateConfigResponse,
  CreateConfigError,
  Options<CreateConfigData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateConfigResponse,
    CreateConfigError,
    Options<CreateConfigData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createConfig({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a config
 */
export const deleteConfigMutation = (
  options?: Partial<Options<DeleteConfigData>>,
): UseMutationOptions<
  DeleteConfigResponse,
  DeleteConfigError,
  Options<DeleteConfigData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteConfigResponse,
    DeleteConfigError,
    Options<DeleteConfigData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteConfig({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update a config
 */
export const updateConfigMutation = (
  options?: Partial<Options<UpdateConfigData>>,
): UseMutationOptions<
  UpdateConfigResponse,
  UpdateConfigError,
  Options<UpdateConfigData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateConfigResponse,
    UpdateConfigError,
    Options<UpdateConfigData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateConfig({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Authenticate user and return access token
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    LoginError,
    Options<LoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh access token using refresh token cookie
 */
export const refreshTokenMutation = (
  options?: Partial<Options<RefreshTokenData>>,
): UseMutationOptions<
  RefreshTokenResponse,
  RefreshTokenError,
  Options<RefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshTokenResponse,
    RefreshTokenError,
    Options<RefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout and invalidate tokens
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    LogoutError,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
