/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard/projects'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardUsersIdRouteImport } from './routes/_dashboard/users/$id'
import { Route as DashboardProjectsNewRouteImport } from './routes/_dashboard/projects/new'
import { Route as DashboardProjectsSlugRouteImport } from './routes/_dashboard/projects/$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsSlugRoute = DashboardProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/users': typeof DashboardUsersRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/projects/$slug': typeof DashboardProjectsSlugRoute
  '/projects/new': typeof DashboardProjectsNewRoute
  '/users/$id': typeof DashboardUsersIdRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/projects/$slug': typeof DashboardProjectsSlugRoute
  '/projects/new': typeof DashboardProjectsNewRoute
  '/users/$id': typeof DashboardUsersIdRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/users': typeof DashboardUsersRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/projects/$slug': typeof DashboardProjectsSlugRoute
  '/_dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/_dashboard/users/$id': typeof DashboardUsersIdRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/projects'
    | '/users'
    | '/'
    | '/projects/$slug'
    | '/projects/new'
    | '/users/$id'
    | '/projects/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/projects/$slug'
    | '/projects/new'
    | '/users/$id'
    | '/projects'
    | '/users'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/projects'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/projects/$slug'
    | '/_dashboard/projects/new'
    | '/_dashboard/users/$id'
    | '/_dashboard/projects/'
    | '/_dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/users/$id': {
      id: '/_dashboard/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/_dashboard/projects/new': {
      id: '/_dashboard/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$slug': {
      id: '/_dashboard/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof DashboardProjectsSlugRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
  }
}

interface DashboardProjectsRouteChildren {
  DashboardProjectsSlugRoute: typeof DashboardProjectsSlugRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsSlugRoute: DashboardProjectsSlugRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardUsersRouteChildren {
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
