// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AddProjectMembersData,
  AddProjectMembersErrors,
  AddProjectMembersResponses,
  ApplyTemplateData,
  ApplyTemplateErrors,
  ApplyTemplateResponses,
  CheckSlugAvailabilityData,
  CheckSlugAvailabilityResponses,
  CreateConfigData,
  CreateConfigErrors,
  CreateConfigResponses,
  CreateEnvironmentData,
  CreateEnvironmentErrors,
  CreateEnvironmentResponses,
  CreateNetworkData,
  CreateNetworkErrors,
  CreateNetworkResponses,
  CreateProjectData,
  CreateProjectErrors,
  CreateProjectResponses,
  CreateSecretData,
  CreateSecretErrors,
  CreateSecretResponses,
  CreateServiceData,
  CreateServiceErrors,
  CreateServiceResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  CreateVolumeData,
  CreateVolumeErrors,
  CreateVolumeResponses,
  DeleteConfigData,
  DeleteConfigErrors,
  DeleteConfigResponses,
  DeleteEnvironmentData,
  DeleteEnvironmentErrors,
  DeleteEnvironmentResponses,
  DeleteNetworkData,
  DeleteNetworkErrors,
  DeleteNetworkResponses,
  DeleteProjectData,
  DeleteProjectErrors,
  DeleteProjectResponses,
  DeleteSecretData,
  DeleteSecretErrors,
  DeleteSecretResponses,
  DeleteServiceData,
  DeleteServiceErrors,
  DeleteServiceResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  DeleteVolumeData,
  DeleteVolumeErrors,
  DeleteVolumeResponses,
  GetConfigsData,
  GetConfigsErrors,
  GetConfigsResponses,
  GetEnvironmentBySlugData,
  GetEnvironmentBySlugErrors,
  GetEnvironmentBySlugResponses,
  GetEnvironmentsData,
  GetEnvironmentsErrors,
  GetEnvironmentsResponses,
  GetNetworksData,
  GetNetworksErrors,
  GetNetworksResponses,
  GetProjectByIdData,
  GetProjectByIdErrors,
  GetProjectByIdResponses,
  GetProjectBySlugData,
  GetProjectBySlugErrors,
  GetProjectBySlugResponses,
  GetProjectsData,
  GetProjectsResponses,
  GetSecretsData,
  GetSecretsErrors,
  GetSecretsResponses,
  GetServiceByIdData,
  GetServiceByIdErrors,
  GetServiceByIdResponses,
  GetServicesData,
  GetServicesErrors,
  GetServicesResponses,
  GetTemplatesData,
  GetTemplatesResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  GetVolumesData,
  GetVolumesErrors,
  GetVolumesResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  RefreshTokenData,
  RefreshTokenErrors,
  RefreshTokenResponses,
  RemoveProjectMembersData,
  RemoveProjectMembersErrors,
  RemoveProjectMembersResponses,
  UpdateConfigData,
  UpdateConfigErrors,
  UpdateConfigResponses,
  UpdateProjectData,
  UpdateProjectErrors,
  UpdateProjectResponses,
  UpdateSecretData,
  UpdateSecretErrors,
  UpdateSecretResponses,
  UpdateServiceData,
  UpdateServiceErrors,
  UpdateServiceResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all available templates
 */
export const getTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<GetTemplatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetTemplatesResponses, unknown, ThrowOnError>(
    { url: "/api/templates", ...options },
  );

/**
 * Apply a template to create services in an environment
 */
export const applyTemplate = <ThrowOnError extends boolean = false>(
  options: Options<ApplyTemplateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApplyTemplateResponses,
    ApplyTemplateErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/templates/{templateId}/apply",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all volumes in an environment
 */
export const getVolumes = <ThrowOnError extends boolean = false>(
  options: Options<GetVolumesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetVolumesResponses,
    GetVolumesErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/volumes",
    ...options,
  });

/**
 * Create a new volume
 */
export const createVolume = <ThrowOnError extends boolean = false>(
  options: Options<CreateVolumeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateVolumeResponses,
    CreateVolumeErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/volumes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a volume
 */
export const deleteVolume = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVolumeData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteVolumeResponses,
    DeleteVolumeErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/volumes/{volumeId}",
    ...options,
  });

/**
 * Get all users (Admin only)
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUsersResponses,
    GetUsersErrors,
    ThrowOnError
  >({ url: "/api/users", ...options });

/**
 * Create a new user (Admin only)
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a user (Admin only)
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({ url: "/api/users/{id}", ...options });

/**
 * Get user by ID (Admin only)
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({ url: "/api/users/{id}", ...options });

/**
 * Update a user (Admin only)
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all services in an environment
 */
export const getServices = <ThrowOnError extends boolean = false>(
  options: Options<GetServicesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetServicesResponses,
    GetServicesErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/services",
    ...options,
  });

/**
 * Create a new service
 */
export const createService = <ThrowOnError extends boolean = false>(
  options: Options<CreateServiceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateServiceResponses,
    CreateServiceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/services",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a service
 */
export const deleteService = <ThrowOnError extends boolean = false>(
  options: Options<DeleteServiceData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteServiceResponses,
    DeleteServiceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/services/{serviceId}",
    ...options,
  });

/**
 * Get service details by ID
 */
export const getServiceById = <ThrowOnError extends boolean = false>(
  options: Options<GetServiceByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetServiceByIdResponses,
    GetServiceByIdErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/services/{serviceId}",
    ...options,
  });

/**
 * Update a service
 */
export const updateService = <ThrowOnError extends boolean = false>(
  options: Options<UpdateServiceData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateServiceResponses,
    UpdateServiceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/services/{serviceId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all secrets in an environment
 */
export const getSecrets = <ThrowOnError extends boolean = false>(
  options: Options<GetSecretsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSecretsResponses,
    GetSecretsErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/secrets",
    ...options,
  });

/**
 * Create a new secret
 */
export const createSecret = <ThrowOnError extends boolean = false>(
  options: Options<CreateSecretData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSecretResponses,
    CreateSecretErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/secrets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a secret
 */
export const deleteSecret = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecretData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSecretResponses,
    DeleteSecretErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/secrets/{secretId}",
    ...options,
  });

/**
 * Update a secret
 */
export const updateSecret = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSecretData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateSecretResponses,
    UpdateSecretErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/secrets/{secretId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all projects for the current user
 */
export const getProjects = <ThrowOnError extends boolean = false>(
  options?: Options<GetProjectsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetProjectsResponses, unknown, ThrowOnError>({
    url: "/api/projects",
    ...options,
  });

/**
 * Create a new project (Admin only)
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateProjectResponses,
    CreateProjectErrors,
    ThrowOnError
  >({
    url: "/api/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a project (Admin only)
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteProjectResponses,
    DeleteProjectErrors,
    ThrowOnError
  >({ url: "/api/projects/{id}", ...options });

/**
 * Get project by ID
 */
export const getProjectById = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectByIdResponses,
    GetProjectByIdErrors,
    ThrowOnError
  >({ url: "/api/projects/{id}", ...options });

/**
 * Update a project (Admin only)
 */
export const updateProject = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateProjectResponses,
    UpdateProjectErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get project by slug
 */
export const getProjectBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectBySlugResponses,
    GetProjectBySlugErrors,
    ThrowOnError
  >({ url: "/api/projects/slug/{slug}", ...options });

/**
 * Check if a slug is available
 */
export const checkSlugAvailability = <ThrowOnError extends boolean = false>(
  options: Options<CheckSlugAvailabilityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CheckSlugAvailabilityResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/projects/check-slug", ...options });

/**
 * Add members to a project (Admin only)
 */
export const addProjectMembers = <ThrowOnError extends boolean = false>(
  options: Options<AddProjectMembersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddProjectMembersResponses,
    AddProjectMembersErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove members from a project (Admin only)
 */
export const removeProjectMembers = <ThrowOnError extends boolean = false>(
  options: Options<RemoveProjectMembersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RemoveProjectMembersResponses,
    RemoveProjectMembersErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}/members/remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all networks in an environment
 */
export const getNetworks = <ThrowOnError extends boolean = false>(
  options: Options<GetNetworksData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetNetworksResponses,
    GetNetworksErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/networks",
    ...options,
  });

/**
 * Create a new network
 */
export const createNetwork = <ThrowOnError extends boolean = false>(
  options: Options<CreateNetworkData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateNetworkResponses,
    CreateNetworkErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/networks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a network
 */
export const deleteNetwork = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNetworkData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteNetworkResponses,
    DeleteNetworkErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/networks/{networkId}",
    ...options,
  });

/**
 * Get all environments for a project
 */
export const getEnvironments = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEnvironmentsResponses,
    GetEnvironmentsErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments", ...options });

/**
 * Create a new environment (Admin only)
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an environment (Admin only)
 */
export const deleteEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEnvironmentResponses,
    DeleteEnvironmentErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments/{envSlug}", ...options });

/**
 * Get environment details by slug
 */
export const getEnvironmentBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEnvironmentBySlugResponses,
    GetEnvironmentBySlugErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments/{envSlug}", ...options });

/**
 * Get all configs in an environment
 */
export const getConfigs = <ThrowOnError extends boolean = false>(
  options: Options<GetConfigsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetConfigsResponses,
    GetConfigsErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/configs",
    ...options,
  });

/**
 * Create a new config
 */
export const createConfig = <ThrowOnError extends boolean = false>(
  options: Options<CreateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateConfigResponses,
    CreateConfigErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/configs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a config
 */
export const deleteConfig = <ThrowOnError extends boolean = false>(
  options: Options<DeleteConfigData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteConfigResponses,
    DeleteConfigErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/configs/{configId}",
    ...options,
  });

/**
 * Update a config
 */
export const updateConfig = <ThrowOnError extends boolean = false>(
  options: Options<UpdateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateConfigResponses,
    UpdateConfigErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/configs/{configId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Authenticate user and return access token
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh access token using refresh token cookie
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshTokenResponses,
    RefreshTokenErrors,
    ThrowOnError
  >({ url: "/api/auth/refresh", ...options });

/**
 * Logout and invalidate tokens
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    { url: "/api/auth/logout", ...options },
  );
