// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AddProjectMembersData,
  AddProjectMembersErrors,
  AddProjectMembersResponses,
  CheckSlugAvailabilityData,
  CheckSlugAvailabilityResponses,
  CreateEnvironmentData,
  CreateEnvironmentErrors,
  CreateEnvironmentResponses,
  CreatePostgreSqlResourceData,
  CreatePostgreSqlResourceErrors,
  CreatePostgreSqlResourceResponses,
  CreateProjectData,
  CreateProjectErrors,
  CreateProjectResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteEnvironmentData,
  DeleteEnvironmentErrors,
  DeleteEnvironmentResponses,
  DeleteProjectData,
  DeleteProjectErrors,
  DeleteProjectResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  DeployResourceData,
  DeployResourceErrors,
  DeployResourceResponses,
  GetEnvironmentBySlugData,
  GetEnvironmentBySlugErrors,
  GetEnvironmentBySlugResponses,
  GetEnvironmentsData,
  GetEnvironmentsErrors,
  GetEnvironmentsResponses,
  GetProjectByIdData,
  GetProjectByIdErrors,
  GetProjectByIdResponses,
  GetProjectBySlugData,
  GetProjectBySlugErrors,
  GetProjectBySlugResponses,
  GetProjectsData,
  GetProjectsResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  RefreshTokenData,
  RefreshTokenErrors,
  RefreshTokenResponses,
  RemoveProjectMembersData,
  RemoveProjectMembersErrors,
  RemoveProjectMembersResponses,
  StopResourceData,
  StopResourceErrors,
  StopResourceResponses,
  UpdateProjectData,
  UpdateProjectErrors,
  UpdateProjectResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all users (Admin only)
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUsersResponses,
    GetUsersErrors,
    ThrowOnError
  >({ url: "/api/users", ...options });

/**
 * Create a new user (Admin only)
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a user (Admin only)
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({ url: "/api/users/{id}", ...options });

/**
 * Get user by ID (Admin only)
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({ url: "/api/users/{id}", ...options });

/**
 * Update a user (Admin only)
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create a new PostgreSQL resource
 */
export const createPostgreSqlResource = <ThrowOnError extends boolean = false>(
  options: Options<CreatePostgreSqlResourceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreatePostgreSqlResourceResponses,
    CreatePostgreSqlResourceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/resources/postgresql",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deploy a resource
 */
export const deployResource = <ThrowOnError extends boolean = false>(
  options: Options<DeployResourceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeployResourceResponses,
    DeployResourceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/resources/{resourceId}/deploy",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Stop a resource
 */
export const stopResource = <ThrowOnError extends boolean = false>(
  options: Options<StopResourceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StopResourceResponses,
    StopResourceErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments/{envSlug}/resources/{resourceId}/stop",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all projects for the current user
 */
export const getProjects = <ThrowOnError extends boolean = false>(
  options?: Options<GetProjectsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetProjectsResponses, unknown, ThrowOnError>({
    url: "/api/projects",
    ...options,
  });

/**
 * Create a new project (Admin only)
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateProjectResponses,
    CreateProjectErrors,
    ThrowOnError
  >({
    url: "/api/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a project (Admin only)
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteProjectResponses,
    DeleteProjectErrors,
    ThrowOnError
  >({ url: "/api/projects/{id}", ...options });

/**
 * Get project by ID
 */
export const getProjectById = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectByIdResponses,
    GetProjectByIdErrors,
    ThrowOnError
  >({ url: "/api/projects/{id}", ...options });

/**
 * Update a project (Admin only)
 */
export const updateProject = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateProjectResponses,
    UpdateProjectErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get project by slug
 */
export const getProjectBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectBySlugResponses,
    GetProjectBySlugErrors,
    ThrowOnError
  >({ url: "/api/projects/slug/{slug}", ...options });

/**
 * Check if a slug is available
 */
export const checkSlugAvailability = <ThrowOnError extends boolean = false>(
  options: Options<CheckSlugAvailabilityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CheckSlugAvailabilityResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/projects/check-slug", ...options });

/**
 * Add members to a project (Admin only)
 */
export const addProjectMembers = <ThrowOnError extends boolean = false>(
  options: Options<AddProjectMembersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddProjectMembersResponses,
    AddProjectMembersErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove members from a project (Admin only)
 */
export const removeProjectMembers = <ThrowOnError extends boolean = false>(
  options: Options<RemoveProjectMembersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RemoveProjectMembersResponses,
    RemoveProjectMembersErrors,
    ThrowOnError
  >({
    url: "/api/projects/{id}/members/remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all environments for a project
 */
export const getEnvironments = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEnvironmentsResponses,
    GetEnvironmentsErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments", ...options });

/**
 * Create a new environment (Admin only)
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    url: "/api/projects/{projectSlug}/environments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an environment (Admin only)
 */
export const deleteEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEnvironmentResponses,
    DeleteEnvironmentErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments/{envSlug}", ...options });

/**
 * Get environment details by slug
 */
export const getEnvironmentBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEnvironmentBySlugResponses,
    GetEnvironmentBySlugErrors,
    ThrowOnError
  >({ url: "/api/projects/{projectSlug}/environments/{envSlug}", ...options });

/**
 * Authenticate user and return access token
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh access token using refresh token cookie
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshTokenResponses,
    RefreshTokenErrors,
    ThrowOnError
  >({ url: "/api/auth/refresh", ...options });

/**
 * Logout and invalidate tokens
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    { url: "/api/auth/logout", ...options },
  );
