// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddProjectMembersData, AddProjectMembersErrors, AddProjectMembersResponses, CreateProjectData, CreateProjectErrors, CreateProjectResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, DeployProjectData, DeployProjectErrors, DeployProjectResponses, GetProjectByIdData, GetProjectByIdErrors, GetProjectByIdResponses, GetProjectDockerStatusData, GetProjectDockerStatusErrors, GetProjectDockerStatusResponses, GetProjectLogsData, GetProjectLogsErrors, GetProjectLogsResponses, GetProjectsData, GetProjectsResponses, GetUserByIdData, GetUserByIdErrors, GetUserByIdResponses, GetUsersData, GetUsersErrors, GetUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, RemoveProjectContainersData, RemoveProjectContainersErrors, RemoveProjectContainersResponses, RemoveProjectMembersData, RemoveProjectMembersErrors, RemoveProjectMembersResponses, RestartProjectData, RestartProjectErrors, RestartProjectResponses, StopProjectData, StopProjectErrors, StopProjectResponses, UpdateComposeFileData, UpdateComposeFileErrors, UpdateComposeFileResponses, UpdateProjectData, UpdateProjectErrors, UpdateProjectResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all users (Admin only)
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({ url: '/api/users', ...options });

/**
 * Create a new user (Admin only)
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a user (Admin only)
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({ url: '/api/users/{id}', ...options });

/**
 * Get user by ID (Admin only)
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError>({ url: '/api/users/{id}', ...options });

/**
 * Update a user (Admin only)
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all projects for the current user
 */
export const getProjects = <ThrowOnError extends boolean = false>(options?: Options<GetProjectsData, ThrowOnError>) => (options?.client ?? client).get<GetProjectsResponses, unknown, ThrowOnError>({ url: '/api/projects', ...options });

/**
 * Create a new project (Admin only)
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>) => (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
    url: '/api/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a project (Admin only)
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({ url: '/api/projects/{id}', ...options });

/**
 * Get project by ID
 */
export const getProjectById = <ThrowOnError extends boolean = false>(options: Options<GetProjectByIdData, ThrowOnError>) => (options.client ?? client).get<GetProjectByIdResponses, GetProjectByIdErrors, ThrowOnError>({ url: '/api/projects/{id}', ...options });

/**
 * Update a project (Admin only)
 */
export const updateProject = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectData, ThrowOnError>) => (options.client ?? client).put<UpdateProjectResponses, UpdateProjectErrors, ThrowOnError>({
    url: '/api/projects/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add members to a project (Admin only)
 */
export const addProjectMembers = <ThrowOnError extends boolean = false>(options: Options<AddProjectMembersData, ThrowOnError>) => (options.client ?? client).post<AddProjectMembersResponses, AddProjectMembersErrors, ThrowOnError>({
    url: '/api/projects/{id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove members from a project (Admin only)
 */
export const removeProjectMembers = <ThrowOnError extends boolean = false>(options: Options<RemoveProjectMembersData, ThrowOnError>) => (options.client ?? client).post<RemoveProjectMembersResponses, RemoveProjectMembersErrors, ThrowOnError>({
    url: '/api/projects/{id}/members/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update project compose file (Admin only)
 */
export const updateComposeFile = <ThrowOnError extends boolean = false>(options: Options<UpdateComposeFileData, ThrowOnError>) => (options.client ?? client).put<UpdateComposeFileResponses, UpdateComposeFileErrors, ThrowOnError>({
    url: '/api/projects/{projectId}/docker/compose',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deploy project containers (Admin only)
 */
export const deployProject = <ThrowOnError extends boolean = false>(options: Options<DeployProjectData, ThrowOnError>) => (options.client ?? client).post<DeployProjectResponses, DeployProjectErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker/deploy', ...options });

/**
 * Stop project containers (Admin only)
 */
export const stopProject = <ThrowOnError extends boolean = false>(options: Options<StopProjectData, ThrowOnError>) => (options.client ?? client).post<StopProjectResponses, StopProjectErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker/stop', ...options });

/**
 * Restart project containers (Admin only)
 */
export const restartProject = <ThrowOnError extends boolean = false>(options: Options<RestartProjectData, ThrowOnError>) => (options.client ?? client).post<RestartProjectResponses, RestartProjectErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker/restart', ...options });

/**
 * Remove project containers and deployment files (Admin only)
 */
export const removeProjectContainers = <ThrowOnError extends boolean = false>(options: Options<RemoveProjectContainersData, ThrowOnError>) => (options.client ?? client).delete<RemoveProjectContainersResponses, RemoveProjectContainersErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker', ...options });

/**
 * Get project deployment status
 */
export const getProjectDockerStatus = <ThrowOnError extends boolean = false>(options: Options<GetProjectDockerStatusData, ThrowOnError>) => (options.client ?? client).get<GetProjectDockerStatusResponses, GetProjectDockerStatusErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker/status', ...options });

/**
 * Get project container logs
 */
export const getProjectLogs = <ThrowOnError extends boolean = false>(options: Options<GetProjectLogsData, ThrowOnError>) => (options.client ?? client).get<GetProjectLogsResponses, GetProjectLogsErrors, ThrowOnError>({ url: '/api/projects/{projectId}/docker/logs', ...options });

/**
 * Authenticate user and return access token
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access token using refresh token cookie
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({ url: '/api/auth/refresh', ...options });

/**
 * Logout and invalidate tokens
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({ url: '/api/auth/logout', ...options });
