// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://localhost:7073/" | (string & {});
};

export type AddMembersRequest = {
  userIds: Array<string>;
};

export type CreateEnvironmentRequest = {
  name: string;
  description: null | string;
};

export type CreateProjectRequest = {
  name: string;
  description: null | string;
  memberIds: null | Array<string>;
};

export type CreateUserRequest = {
  email: string;
  displayName: string;
  password: string;
};

export type EnvironmentDetailDto = {
  id: string;
  name: string;
  slug: string;
  description: null | string;
  projectId: string;
  isDefault: boolean;
  createdAt: string;
  variables: Array<EnvironmentVariableDto>;
  resources: Array<ResourceSummaryDto>;
};

export type EnvironmentDto = {
  id: string;
  name: string;
  slug: string;
  description: null | string;
  projectId: string;
  isDefault: boolean;
  createdAt: string;
  variableCount: number | string;
  resourceCount: number | string;
};

export type EnvironmentVariableDto = {
  id: string;
  key: string;
  value: string;
  isSecret: boolean;
  createdAt: string;
};

export type HttpValidationProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
  errors?: {
    [key: string]: Array<string>;
  };
};

export type LoginApiResponse = {
  accessToken: string;
  accessTokenExpiresAt: string;
  user: UserDto;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
};

export type ProjectDto = {
  id: string;
  name: string;
  slug: string;
  description: null | string;
  createdByUserId: string;
  createdAt: string;
  updatedAt: null | string;
  environmentCount: number | string;
  members: Array<ProjectMemberDto>;
  environments: Array<ProjectEnvironmentDto>;
};

export type ProjectEnvironmentDto = {
  id: string;
  name: string;
  slug: string;
  isDefault: boolean;
};

export type ProjectMemberDto = {
  userId: string;
  email: string;
  displayName: string;
  joinedAt: string;
};

export type RefreshApiResponse = {
  accessToken: string;
  accessTokenExpiresAt: string;
  user: UserDto;
};

export type RemoveMembersRequest = {
  userIds: Array<string>;
};

export type ResourceSummaryDto = {
  id: string;
  name: string;
  type: string;
  status: string;
};

export type SlugAvailabilityResponse = {
  isAvailable: boolean;
  suggestedSlug: null | string;
};

export type UpdateProjectRequest = {
  name: string;
  description: null | string;
};

export type UpdateUserRequest = {
  displayName: string;
  email: null | string;
};

export type UserDto = {
  id: string;
  email: string;
  displayName: string;
  isAdmin: boolean;
  createdAt: string;
  updatedAt: null | string;
};

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number | string;
  };
  url: "/api/users";
};

export type GetUsersErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<UserDto>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type CreateUserErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Created
   */
  201: UserDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type DeleteUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetUserByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type GetUserByIdErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
  body: UpdateUserRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UpdateUserErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetProjectsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number | string;
  };
  url: "/api/projects";
};

export type GetProjectsResponses = {
  /**
   * OK
   */
  200: Array<ProjectDto>;
};

export type GetProjectsResponse =
  GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
  body: CreateProjectRequest;
  path?: never;
  query?: never;
  url: "/api/projects";
};

export type CreateProjectErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
  /**
   * Created
   */
  201: ProjectDto;
};

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/projects/{id}";
};

export type DeleteProjectErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetProjectByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/projects/{id}";
};

export type GetProjectByIdErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProjectByIdError =
  GetProjectByIdErrors[keyof GetProjectByIdErrors];

export type GetProjectByIdResponses = {
  /**
   * OK
   */
  200: ProjectDto;
};

export type GetProjectByIdResponse =
  GetProjectByIdResponses[keyof GetProjectByIdResponses];

export type UpdateProjectData = {
  body: UpdateProjectRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/projects/{id}";
};

export type UpdateProjectErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
  /**
   * OK
   */
  200: ProjectDto;
};

export type UpdateProjectResponse =
  UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetProjectBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: "/api/projects/slug/{slug}";
};

export type GetProjectBySlugErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProjectBySlugError =
  GetProjectBySlugErrors[keyof GetProjectBySlugErrors];

export type GetProjectBySlugResponses = {
  /**
   * OK
   */
  200: ProjectDto;
};

export type GetProjectBySlugResponse =
  GetProjectBySlugResponses[keyof GetProjectBySlugResponses];

export type CheckSlugAvailabilityData = {
  body?: never;
  path?: never;
  query: {
    Slug: string;
  };
  url: "/api/projects/check-slug";
};

export type CheckSlugAvailabilityResponses = {
  /**
   * OK
   */
  200: SlugAvailabilityResponse;
};

export type CheckSlugAvailabilityResponse =
  CheckSlugAvailabilityResponses[keyof CheckSlugAvailabilityResponses];

export type AddProjectMembersData = {
  body: AddMembersRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/projects/{id}/members";
};

export type AddProjectMembersErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AddProjectMembersError =
  AddProjectMembersErrors[keyof AddProjectMembersErrors];

export type AddProjectMembersResponses = {
  /**
   * OK
   */
  200: ProjectDto;
};

export type AddProjectMembersResponse =
  AddProjectMembersResponses[keyof AddProjectMembersResponses];

export type RemoveProjectMembersData = {
  body: RemoveMembersRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/projects/{id}/members/remove";
};

export type RemoveProjectMembersErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type RemoveProjectMembersError =
  RemoveProjectMembersErrors[keyof RemoveProjectMembersErrors];

export type RemoveProjectMembersResponses = {
  /**
   * OK
   */
  200: ProjectDto;
};

export type RemoveProjectMembersResponse =
  RemoveProjectMembersResponses[keyof RemoveProjectMembersResponses];

export type GetEnvironmentsData = {
  body?: never;
  path: {
    projectSlug: string;
  };
  query?: never;
  url: "/api/projects/{projectSlug}/environments";
};

export type GetEnvironmentsErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetEnvironmentsError =
  GetEnvironmentsErrors[keyof GetEnvironmentsErrors];

export type GetEnvironmentsResponses = {
  /**
   * OK
   */
  200: Array<EnvironmentDto>;
};

export type GetEnvironmentsResponse =
  GetEnvironmentsResponses[keyof GetEnvironmentsResponses];

export type CreateEnvironmentData = {
  body: CreateEnvironmentRequest;
  path: {
    projectSlug: string;
  };
  query?: never;
  url: "/api/projects/{projectSlug}/environments";
};

export type CreateEnvironmentErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type CreateEnvironmentError =
  CreateEnvironmentErrors[keyof CreateEnvironmentErrors];

export type CreateEnvironmentResponses = {
  /**
   * Created
   */
  201: EnvironmentDto;
};

export type CreateEnvironmentResponse =
  CreateEnvironmentResponses[keyof CreateEnvironmentResponses];

export type DeleteEnvironmentData = {
  body?: never;
  path: {
    projectSlug: string;
    envSlug: string;
  };
  query?: never;
  url: "/api/projects/{projectSlug}/environments/{envSlug}";
};

export type DeleteEnvironmentErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteEnvironmentError =
  DeleteEnvironmentErrors[keyof DeleteEnvironmentErrors];

export type DeleteEnvironmentResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteEnvironmentResponse =
  DeleteEnvironmentResponses[keyof DeleteEnvironmentResponses];

export type GetEnvironmentBySlugData = {
  body?: never;
  path: {
    projectSlug: string;
    envSlug: string;
  };
  query?: never;
  url: "/api/projects/{projectSlug}/environments/{envSlug}";
};

export type GetEnvironmentBySlugErrors = {
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetEnvironmentBySlugError =
  GetEnvironmentBySlugErrors[keyof GetEnvironmentBySlugErrors];

export type GetEnvironmentBySlugResponses = {
  /**
   * OK
   */
  200: EnvironmentDetailDto;
};

export type GetEnvironmentBySlugResponse =
  GetEnvironmentBySlugResponses[keyof GetEnvironmentBySlugResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type LoginErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * OK
   */
  200: LoginApiResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type RefreshTokenErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
  /**
   * OK
   */
  200: RefreshApiResponse;
};

export type RefreshTokenResponse =
  RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type LogoutErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
