// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7073/' | (string & {});
};

export type CreateUserRequest = {
    email: string;
    displayName: string;
    password: string;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type LoginApiResponse = {
    accessToken: string;
    accessTokenExpiresAt: string;
    user: UserDto;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RefreshApiResponse = {
    accessToken: string;
    accessTokenExpiresAt: string;
    user: UserDto;
};

export type UpdateUserRequest = {
    displayName: string;
    email: null | string;
};

export type UserDto = {
    id: string;
    email: string;
    displayName: string;
    isAdmin: boolean;
    createdAt: string;
    updatedAt: null | string;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number | string;
    };
    url: '/api/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Created
     */
    201: UserDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginApiResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: RefreshApiResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
