// <auto-generated />
using System;
using BaseDock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseDock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseDock.Domain.Entities.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("External")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external");

                    b.Property<string>("ExternalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("configs", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComposeFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("compose_file_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique();

                    b.ToTable("environments", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Network", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Attachable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("attachable");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Driver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("driver");

                    b.Property<string>("DriverOpts")
                        .HasColumnType("jsonb")
                        .HasColumnName("driver_opts");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("External")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external");

                    b.Property<string>("ExternalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_name");

                    b.Property<bool>("Internal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("internal");

                    b.Property<string>("IpamConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("ipam_config");

                    b.Property<string>("IpamDriver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ipam_driver");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("External")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external");

                    b.Property<string>("ExternalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("secrets", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildArgs")
                        .HasColumnType("jsonb")
                        .HasColumnName("build_args");

                    b.Property<string>("BuildContext")
                        .HasColumnType("text")
                        .HasColumnName("build_context");

                    b.Property<string>("BuildDockerfile")
                        .HasColumnType("text")
                        .HasColumnName("build_dockerfile");

                    b.PrimitiveCollection<string[]>("Command")
                        .HasColumnType("text[]")
                        .HasColumnName("command");

                    b.Property<string>("CpuLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpu_limit");

                    b.Property<string>("CpuReservation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpu_reservation");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DependsOn")
                        .HasColumnType("jsonb")
                        .HasColumnName("depends_on");

                    b.Property<int>("DeploymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("deployment_status");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("Dns")
                        .HasColumnType("text[]")
                        .HasColumnName("dns");

                    b.Property<string>("Domainname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domainname");

                    b.PrimitiveCollection<string[]>("Entrypoint")
                        .HasColumnType("text[]")
                        .HasColumnName("entrypoint");

                    b.PrimitiveCollection<string[]>("EnvFile")
                        .HasColumnType("text[]")
                        .HasColumnName("env_file");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("jsonb")
                        .HasColumnName("environment_variables");

                    b.PrimitiveCollection<int[]>("Expose")
                        .HasColumnType("integer[]")
                        .HasColumnName("expose");

                    b.Property<string>("ExtraHosts")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_hosts");

                    b.Property<bool>("HealthcheckDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("healthcheck_disabled");

                    b.Property<string>("HealthcheckInterval")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("healthcheck_interval");

                    b.Property<int?>("HealthcheckRetries")
                        .HasColumnType("integer")
                        .HasColumnName("healthcheck_retries");

                    b.Property<string>("HealthcheckStartPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("healthcheck_start_period");

                    b.PrimitiveCollection<string[]>("HealthcheckTest")
                        .HasColumnType("text[]")
                        .HasColumnName("healthcheck_test");

                    b.Property<string>("HealthcheckTimeout")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("healthcheck_timeout");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<DateTimeOffset?>("LastDeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_deployed_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.PrimitiveCollection<string[]>("Links")
                        .HasColumnType("text[]")
                        .HasColumnName("links");

                    b.Property<string>("MemoryLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("memory_limit");

                    b.Property<string>("MemoryReservation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("memory_reservation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Ports")
                        .HasColumnType("jsonb")
                        .HasColumnName("ports");

                    b.Property<int>("Replicas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("replicas");

                    b.Property<string>("Restart")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("restart");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("StopGracePeriod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stop_grace_period");

                    b.Property<string>("StopSignal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stop_signal");

                    b.PrimitiveCollection<string[]>("Tmpfs")
                        .HasColumnType("text[]")
                        .HasColumnName("tmpfs");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user");

                    b.Property<string>("Volumes")
                        .HasColumnType("jsonb")
                        .HasColumnName("volumes");

                    b.Property<string>("WorkingDir")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("working_dir");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Slug")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceConfig", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<string>("Gid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gid");

                    b.Property<string>("Mode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mode");

                    b.Property<string>("Target")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target");

                    b.Property<string>("Uid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uid");

                    b.HasKey("ServiceId", "ConfigId");

                    b.HasIndex("ConfigId");

                    b.ToTable("service_configs", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceNetwork", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Ipv4Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ipv4_address");

                    b.Property<string>("Ipv6Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ipv6_address");

                    b.HasKey("ServiceId", "NetworkId");

                    b.HasIndex("NetworkId");

                    b.ToTable("service_networks", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceSecret", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<string>("Gid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gid");

                    b.Property<string>("Mode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mode");

                    b.Property<string>("Target")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target");

                    b.Property<string>("Uid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uid");

                    b.HasKey("ServiceId", "SecretId");

                    b.HasIndex("SecretId");

                    b.ToTable("service_secrets", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Driver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("driver");

                    b.Property<string>("DriverOpts")
                        .HasColumnType("jsonb")
                        .HasColumnName("driver_opts");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("External")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external");

                    b.Property<string>("ExternalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_name");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("volumes", (string)null);
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Config", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Environment", "Environment")
                        .WithMany("Configs")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Environment", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Network", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Environment", "Environment")
                        .WithMany("Networks")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Project", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseDock.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Secret", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Environment", "Environment")
                        .WithMany("Secrets")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Service", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Environment", "ParentEnvironment")
                        .WithMany("Services")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentEnvironment");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceConfig", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Config", "Config")
                        .WithMany("ServiceConfigs")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseDock.Domain.Entities.Service", "Service")
                        .WithMany("ServiceConfigs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceNetwork", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Network", "Network")
                        .WithMany("ServiceNetworks")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseDock.Domain.Entities.Service", "Service")
                        .WithMany("ServiceNetworks")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.ServiceSecret", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Secret", "Secret")
                        .WithMany("ServiceSecrets")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseDock.Domain.Entities.Service", "Service")
                        .WithMany("ServiceSecrets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secret");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Volume", b =>
                {
                    b.HasOne("BaseDock.Domain.Entities.Environment", "Environment")
                        .WithMany("Volumes")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Config", b =>
                {
                    b.Navigation("ServiceConfigs");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Environment", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("Networks");

                    b.Navigation("Secrets");

                    b.Navigation("Services");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Network", b =>
                {
                    b.Navigation("ServiceNetworks");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Secret", b =>
                {
                    b.Navigation("ServiceSecrets");
                });

            modelBuilder.Entity("BaseDock.Domain.Entities.Service", b =>
                {
                    b.Navigation("ServiceConfigs");

                    b.Navigation("ServiceNetworks");

                    b.Navigation("ServiceSecrets");
                });
#pragma warning restore 612, 618
        }
    }
}
